### ISSUE TITLE
Update list of symptoms

### ISSUE THREAD

**Issue by rmehner** [eHealthAfrica/symptoms#13]
See https://github.com/eHealthAfrica/sense-followup/issues/338 for details.

**Comment by ni-ka** [comment]
Here is the parsed List:

Fever
Muscles or joints 
Joint pain
Neck rigidity
Weakness
Nausea and vomiting
Diarrhea (non-bloody / bloody)
Abdominal pain
Headache
Back ache
Chest pain
Sore throat or swallowing
Rash
Bruising
Red eyes
Any bleeding
Jaundice
Other symptoms

**Comment by rmehner** [comment]
> Any bleeding

"Unexplained bleedings", is this the same?

**Comment by rmehner** [comment]
> Neck rigidity

My babel skills fail me, do you have a french translation handy for this?

**Comment by rmehner** [comment]
Correct me if I'm wrong, the only new symptom in there is indeed `Neck rigidity`, right? Some of the symptoms you mentioned are just synonyms for existing ones (e.g. weakness is intense fatigue).
